-- =============================================================================
--  CATÁLOGO DE PERFUMES · Supabase
--  Pegá TODO este archivo en Supabase → SQL Editor → New query → Run.
--  Se puede volver a correr sin problemas: no duplica tablas, políticas ni datos.
--
--  DESPUÉS DE CORRERLO:
--   1) Authentication → Users → "Add user" → "Create new user": tu email y una
--      contraseña (tildá "Auto Confirm User"). Ese es el login del panel /admin.
--   2) ⚠ CERRÁ EL REGISTRO PÚBLICO. Supabase lo trae ABIERTO de fábrica:
--      Authentication → Sign In / Providers → desactivá "Allow new users to sign up".
--      Si queda abierto, cualquiera puede crearse una cuenta y editar tu catálogo
--      (el panel te muestra un cartel rojo mientras siga abierto).
--   3) Project Settings → API: copiá "Project URL" y la clave "anon public" en
--      assets/js/config.js (supabaseUrl y supabaseAnonKey).
-- =============================================================================


-- ---------------------------------------------------------------- Tablas
create table if not exists public.categorias (
  id     bigint generated by default as identity primary key,
  nombre text not null unique,
  orden  int  not null default 0
);

create table if not exists public.familias (
  id     bigint generated by default as identity primary key,
  nombre text not null unique,
  orden  int  not null default 0
);

create table if not exists public.perfumes (
  id              bigint generated by default as identity primary key,
  nombre          text not null,
  marca           text not null default '',
  categoria       bigint references public.categorias(id) on delete set null,
  familia         bigint references public.familias(id) on delete set null,
  concentracion   text check (concentracion in ('EDT', 'EDP', 'Elixir', 'Extracto')),
  -- {"salida": [...], "corazon": [...], "fondo": [...]}
  notas           jsonb not null default '{"salida": [], "corazon": [], "fondo": []}'::jsonb,
  precio          numeric(12,2) not null check (precio >= 0),
  precio_anterior numeric(12,2) check (precio_anterior is null or precio_anterior >= 0),
  descripcion     text not null default '',
  imagenes        text[] not null default '{}',
  -- "100 ml" o, con precio propio por tamaño, "50 ml: 29900"
  tamanios        text[] not null default '{}',
  tipo            text not null default 'Sellado' check (tipo in ('Sellado', 'Tester', 'Decant')),
  duracion_horas  numeric(4,1) check (duracion_horas is null or duracion_horas between 0 and 48),
  estela          smallint check (estela is null or estela between 1 and 5),
  stock           boolean not null default true,
  etiqueta        text check (etiqueta in ('Importado', 'Nuevo', 'Oferta', 'Más vendido')),
  destacado       boolean not null default false,
  activo          boolean not null default true,
  fecha_creacion  timestamptz not null default now()
);

create index if not exists perfumes_activo_idx on public.perfumes (activo);
create index if not exists perfumes_categoria_idx on public.perfumes (categoria);
create index if not exists perfumes_familia_idx on public.perfumes (familia);


-- ---------------------------------------------------------------- Permisos (GRANT)
-- Las políticas RLS solas no alcanzan: sin estos GRANT todo devuelve
-- "permission denied for table ...".
grant usage on schema public to anon, authenticated;
grant select on public.perfumes, public.categorias, public.familias to anon, authenticated;
grant insert, update, delete on public.perfumes, public.categorias, public.familias to authenticated;
grant usage, select on all sequences in schema public to authenticated;


-- ---------------------------------------------------------------- Row Level Security
alter table public.perfumes   enable row level security;
alter table public.categorias enable row level security;
alter table public.familias   enable row level security;

-- Lectura pública de perfumes activos. Vale para anon Y authenticated: si no,
-- con el panel logueado en el mismo navegador verías tu tienda vacía.
drop policy if exists "perfumes_lectura_publica" on public.perfumes;
create policy "perfumes_lectura_publica" on public.perfumes
  for select to anon, authenticated using (activo = true);

-- Con sesión iniciada (panel) se ven también los inactivos.
drop policy if exists "perfumes_admin_lee_todo" on public.perfumes;
create policy "perfumes_admin_lee_todo" on public.perfumes
  for select to authenticated using (true);

drop policy if exists "perfumes_admin_crea" on public.perfumes;
create policy "perfumes_admin_crea" on public.perfumes
  for insert to authenticated with check (true);

drop policy if exists "perfumes_admin_edita" on public.perfumes;
create policy "perfumes_admin_edita" on public.perfumes
  for update to authenticated using (true) with check (true);

drop policy if exists "perfumes_admin_borra" on public.perfumes;
create policy "perfumes_admin_borra" on public.perfumes
  for delete to authenticated using (true);

-- Categorías y familias: lectura pública, escritura con sesión.
do $$
declare t text;
begin
  foreach t in array array['categorias', 'familias'] loop
    execute format('drop policy if exists %I on public.%I', t || '_lectura_publica', t);
    execute format('create policy %I on public.%I for select to anon, authenticated using (true)', t || '_lectura_publica', t);
    execute format('drop policy if exists %I on public.%I', t || '_admin_escribe', t);
    execute format('create policy %I on public.%I for all to authenticated using (true) with check (true)', t || '_admin_escribe', t);
  end loop;
end $$;


-- ---------------------------------------------------------------- Storage (fotos)
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('perfumes', 'perfumes', true, 5242880, array['image/jpeg', 'image/png', 'image/webp', 'image/avif'])
on conflict (id) do update
  set public = true, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "perfumes_fotos_lectura" on storage.objects;
create policy "perfumes_fotos_lectura" on storage.objects
  for select to anon, authenticated using (bucket_id = 'perfumes');

drop policy if exists "perfumes_fotos_subir" on storage.objects;
create policy "perfumes_fotos_subir" on storage.objects
  for insert to authenticated with check (bucket_id = 'perfumes');

drop policy if exists "perfumes_fotos_editar" on storage.objects;
create policy "perfumes_fotos_editar" on storage.objects
  for update to authenticated using (bucket_id = 'perfumes') with check (bucket_id = 'perfumes');

drop policy if exists "perfumes_fotos_borrar" on storage.objects;
create policy "perfumes_fotos_borrar" on storage.objects
  for delete to authenticated using (bucket_id = 'perfumes');


-- ---------------------------------------------------------------- Datos iniciales
-- Cada bloque se carga SÓLO si la tabla está vacía: volver a correr el script
-- no duplica el catálogo ni pisa lo que cargaste desde el panel.
insert into public.categorias (nombre, orden)
select v.nombre, v.orden
from (values ('Árabes', 1), ('Femeninos', 2), ('Masculinos', 3), ('Unisex', 4), ('Body splash', 5)) as v(nombre, orden)
where not exists (select 1 from public.categorias);

insert into public.familias (nombre, orden)
select v.nombre, v.orden
from (values ('Oriental', 1), ('Floral', 2), ('Cítrico', 3), ('Gourmand', 4), ('Amaderado', 5), ('Acuático', 6)) as v(nombre, orden)
where not exists (select 1 from public.familias);

-- 6 perfumes de ejemplo. Las fotos apuntan a /assets/img/perfumes/ del sitio.
insert into public.perfumes
  (nombre, marca, categoria, familia, concentracion, notas, precio, precio_anterior, descripcion,
   imagenes, tamanios, tipo, duracion_horas, estela, stock, etiqueta, destacado, activo, fecha_creacion)
select
  v.nombre, v.marca,
  (select c.id from public.categorias c where c.nombre = v.cat),
  (select f.id from public.familias f where f.nombre = v.fam),
  v.concentracion, v.notas, v.precio, v.precio_anterior, v.descripcion,
  v.imagenes, v.tamanios, v.tipo, v.duracion_horas, v.estela, v.stock, v.etiqueta, v.destacado, v.activo, v.fecha
from (values
  ('Yara', 'Lattafa', 'Árabes', 'Gourmand', 'EDP', '{"salida":["Orquídea","Heliotropo","Mandarina"],"corazon":["Acorde gourmand","Frutas tropicales"],"fondo":["Vainilla","Almizcle","Sándalo"]}'::jsonb, 39900, null::numeric, 'Dulce, cremoso y muy femenino. La vainilla y las frutas tropicales lo vuelven adictivo: es el árabe que más nos piden para regalar.', array['/assets/img/perfumes/lattafa-yara-1.svg', '/assets/img/perfumes/lattafa-yara-2.svg']::text[], array['100 ml']::text[], 'Sellado', 8, 4, true, 'Más vendido', true, true, '2026-08-02T15:00:00.000Z'::timestamptz),
  ('Odyssey Mandarin Sky', 'Armaf', 'Árabes', 'Cítrico', 'EDP', '{"salida":["Mandarina","Naranja amarga"],"corazon":["Caramelo","Canela"],"fondo":["Haba tonka","Ámbar","Vetiver"]}'::jsonb, 34900, null::numeric, 'Una explosión de mandarina jugosa sobre un fondo dulce de tonka. Fresco de día, envolvente de noche.', array['/assets/img/perfumes/armaf-odyssey-mandarin-sky-1.svg', '/assets/img/perfumes/armaf-odyssey-mandarin-sky-2.svg']::text[], array['100 ml']::text[], 'Sellado', 9, 4, true, 'Nuevo', true, true, '2026-09-10T15:00:00.000Z'::timestamptz),
  ('Khamrah', 'Lattafa', 'Árabes', 'Oriental', 'EDP', '{"salida":["Canela","Nuez moscada","Bergamota"],"corazon":["Dátiles","Praliné","Nardos"],"fondo":["Vainilla","Haba tonka","Benjuí"]}'::jsonb, 45900, 52900, 'Especiado, licoroso y cálido. Dátiles, canela y praliné en un perfume que se siente de lujo y dura todo el día.', array['/assets/img/perfumes/lattafa-khamrah-1.svg', '/assets/img/perfumes/lattafa-khamrah-2.svg']::text[], array['100 ml']::text[], 'Sellado', 10, 5, true, 'Oferta', false, true, '2026-07-20T15:00:00.000Z'::timestamptz),
  ('Good Girl', 'Carolina Herrera', 'Femeninos', 'Floral', 'EDP', '{"salida":["Almendra","Café"],"corazon":["Tuberosa","Jazmín sambac"],"fondo":["Haba tonka","Cacao"]}'::jsonb, 129900, null::numeric, 'El icónico frasco stiletto. Luminoso y oscuro a la vez: flores blancas con un fondo de cacao y tonka.', array['/assets/img/perfumes/carolina-herrera-good-girl-1.svg', '/assets/img/perfumes/carolina-herrera-good-girl-2.svg']::text[], array['50 ml: 129900', '80 ml: 159900']::text[], 'Sellado', 7, 3, false, 'Importado', false, true, '2026-06-15T15:00:00.000Z'::timestamptz),
  ('Sauvage', 'Dior', 'Masculinos', 'Amaderado', 'EDT', '{"salida":["Bergamota de Calabria","Pimienta"],"corazon":["Lavanda","Pimienta de Sichuán","Geranio"],"fondo":["Ambroxan","Cedro","Ládano"]}'::jsonb, 12900, null::numeric, 'Decant del original fraccionado a mano. Ideal para probarlo a fondo antes de comprar el frasco completo.', array['/assets/img/perfumes/dior-sauvage-1.svg', '/assets/img/perfumes/dior-sauvage-2.svg']::text[], array['5 ml: 12900', '10 ml: 22900']::text[], 'Decant', 7, 4, true, null, false, true, '2026-08-25T15:00:00.000Z'::timestamptz),
  ('Bare Vanilla', 'Victoria''s Secret', 'Body splash', 'Gourmand', null, '{"salida":["Vainilla batida"],"corazon":["Cachemira"],"fondo":["Almizcle suave"]}'::jsonb, 19900, 24900, 'Body splash suave y cremoso para usar todos los días y retocar en la cartera.', array['/assets/img/perfumes/victorias-secret-bare-vanilla-1.svg', '/assets/img/perfumes/victorias-secret-bare-vanilla-2.svg']::text[], array['250 ml']::text[], 'Sellado', 3, 2, true, 'Oferta', false, true, '2026-05-30T15:00:00.000Z'::timestamptz)
) as v(nombre, marca, cat, fam, concentracion, notas, precio, precio_anterior, descripcion,
       imagenes, tamanios, tipo, duracion_horas, estela, stock, etiqueta, destacado, activo, fecha)
where not exists (select 1 from public.perfumes);
