-- =============================================================================
--  CATÁLOGO DE PERFUMES · Supabase
--  Se puede volver a correr sin problemas: no duplica tablas, políticas ni datos.
--
--  ORDEN RECOMENDADO:
--   1) Authentication → Users → "Add user" → "Create new user": el email y la
--      contraseña del administrador (tildá "Auto Confirm User").
--   2) ⚠ CERRÁ EL REGISTRO PÚBLICO. Supabase lo trae ABIERTO de fábrica:
--      Authentication → Sign In / Providers → desactivá "Allow new users to sign up".
--   3) SQL Editor → New query → pegá TODO este archivo → Run.
--      La primera vez, los usuarios que ya existan quedan autorizados como
--      administradores. Para sumar otro más adelante:
--        insert into public.admins (email) values ('otro@email.com');
-- =============================================================================


-- ---------------------------------------------------------------- Tablas
create table if not exists public.categorias (
  id     bigint generated by default as identity primary key,
  nombre text not null unique,
  orden  int  not null default 0
);

create table if not exists public.familias (
  id     bigint generated by default as identity primary key,
  nombre text not null unique,
  orden  int  not null default 0
);

create table if not exists public.perfumes (
  id              bigint generated by default as identity primary key,
  nombre          text not null,
  marca           text not null default '',
  categoria       bigint references public.categorias(id) on delete set null,
  familia         bigint references public.familias(id) on delete set null,
  concentracion   text check (concentracion in ('EDT', 'EDP', 'Elixir', 'Extracto')),
  -- {"salida": [...], "corazon": [...], "fondo": [...]}
  notas           jsonb not null default '{"salida": [], "corazon": [], "fondo": []}'::jsonb,
  precio          numeric(12,2) not null check (precio >= 0),
  precio_anterior numeric(12,2) check (precio_anterior is null or precio_anterior >= 0),
  descripcion     text not null default '',
  imagenes        text[] not null default '{}',
  -- "100 ml" o, con precio propio por tamaño, "50 ml: 29900"
  tamanios        text[] not null default '{}',
  tipo            text not null default 'Sellado' check (tipo in ('Sellado', 'Tester', 'Decant')),
  duracion_horas  numeric(4,1) check (duracion_horas is null or duracion_horas between 0 and 48),
  estela          smallint check (estela is null or estela between 1 and 5),
  stock           boolean not null default true,
  etiqueta        text check (etiqueta in ('Importado', 'Nuevo', 'Oferta', 'Más vendido')),
  destacado       boolean not null default false,
  activo          boolean not null default true,
  fecha_creacion  timestamptz not null default now()
);

create index if not exists perfumes_activo_idx on public.perfumes (activo);
create index if not exists perfumes_categoria_idx on public.perfumes (categoria);
create index if not exists perfumes_familia_idx on public.perfumes (familia);


-- ---------------------------------------------------------------- Administradores
-- Sólo los emails de esta tabla pueden editar el catálogo y subir fotos.
-- Tener usuario en Supabase no alcanza: así, aunque alguien lograra crearse una
-- cuenta, no podría tocar nada.
create table if not exists public.admins (
  email text primary key
);
alter table public.admins enable row level security; -- sin políticas: nadie la lee desde la web

create or replace function public.es_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admins
    where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;
revoke all on function public.es_admin() from public;
grant execute on function public.es_admin() to anon, authenticated;

-- Primera vez: autoriza a los usuarios que ya creaste en Authentication → Users.
insert into public.admins (email)
select lower(u.email) from auth.users u
where u.email is not null and not exists (select 1 from public.admins)
on conflict do nothing;


-- ---------------------------------------------------------------- Permisos (GRANT)
-- Las políticas RLS solas no alcanzan: sin estos GRANT todo devuelve
-- "permission denied for table ...".
grant usage on schema public to anon, authenticated;
grant select on public.perfumes, public.categorias, public.familias to anon, authenticated;
grant insert, update, delete on public.perfumes, public.categorias, public.familias to authenticated;
grant usage, select on all sequences in schema public to authenticated;


-- ---------------------------------------------------------------- Row Level Security
alter table public.perfumes   enable row level security;
alter table public.categorias enable row level security;
alter table public.familias   enable row level security;

-- Lectura pública de perfumes activos. Vale para anon Y authenticated: si no,
-- con el panel logueado en el mismo navegador verías tu tienda vacía.
drop policy if exists "perfumes_lectura_publica" on public.perfumes;
create policy "perfumes_lectura_publica" on public.perfumes
  for select to anon, authenticated using (activo = true);

-- El administrador ve también los inactivos y es el único que escribe.
drop policy if exists "perfumes_admin_lee_todo" on public.perfumes;
create policy "perfumes_admin_lee_todo" on public.perfumes
  for select to authenticated using (public.es_admin());

drop policy if exists "perfumes_admin_crea" on public.perfumes;
create policy "perfumes_admin_crea" on public.perfumes
  for insert to authenticated with check (public.es_admin());

drop policy if exists "perfumes_admin_edita" on public.perfumes;
create policy "perfumes_admin_edita" on public.perfumes
  for update to authenticated using (public.es_admin()) with check (public.es_admin());

drop policy if exists "perfumes_admin_borra" on public.perfumes;
create policy "perfumes_admin_borra" on public.perfumes
  for delete to authenticated using (public.es_admin());

-- Categorías y familias: lectura pública, escritura sólo del administrador.
do $$
declare t text;
begin
  foreach t in array array['categorias', 'familias'] loop
    execute format('drop policy if exists %I on public.%I', t || '_lectura_publica', t);
    execute format('create policy %I on public.%I for select to anon, authenticated using (true)', t || '_lectura_publica', t);
    execute format('drop policy if exists %I on public.%I', t || '_admin_escribe', t);
    execute format('create policy %I on public.%I for all to authenticated using (public.es_admin()) with check (public.es_admin())', t || '_admin_escribe', t);
  end loop;
end $$;


-- ---------------------------------------------------------------- Storage (fotos)
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('perfumes', 'perfumes', true, 5242880, array['image/jpeg', 'image/png', 'image/webp', 'image/avif'])
on conflict (id) do update
  set public = true, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "perfumes_fotos_lectura" on storage.objects;
create policy "perfumes_fotos_lectura" on storage.objects
  for select to anon, authenticated using (bucket_id = 'perfumes');

drop policy if exists "perfumes_fotos_subir" on storage.objects;
create policy "perfumes_fotos_subir" on storage.objects
  for insert to authenticated with check (bucket_id = 'perfumes' and public.es_admin());

drop policy if exists "perfumes_fotos_editar" on storage.objects;
create policy "perfumes_fotos_editar" on storage.objects
  for update to authenticated using (bucket_id = 'perfumes' and public.es_admin()) with check (bucket_id = 'perfumes' and public.es_admin());

drop policy if exists "perfumes_fotos_borrar" on storage.objects;
create policy "perfumes_fotos_borrar" on storage.objects
  for delete to authenticated using (bucket_id = 'perfumes' and public.es_admin());


-- ---------------------------------------------------------------- Datos iniciales
-- Sólo si la tabla está vacía: volver a correr el script no duplica nada ni pisa
-- lo que cargaste desde el panel. El catálogo arranca vacío y se carga desde /admin
-- (hay perfumes de ejemplo opcionales en supabase/ejemplos.sql).
insert into public.categorias (nombre, orden)
select v.nombre, v.orden
from (values ('Árabes', 1), ('Femeninos', 2), ('Masculinos', 3), ('Unisex', 4), ('Body splash', 5)) as v(nombre, orden)
where not exists (select 1 from public.categorias);

insert into public.familias (nombre, orden)
select v.nombre, v.orden
from (values ('Oriental', 1), ('Floral', 2), ('Cítrico', 3), ('Gourmand', 4), ('Amaderado', 5), ('Acuático', 6)) as v(nombre, orden)
where not exists (select 1 from public.familias);
